import type { PlanetarySignal, SignalsResponse } from "./types";

const demoSeeds: Array<Omit<PlanetarySignal, "observedAt"> & { minutesAgo: number }> = [
  {
    id: "sample-eq-kuril",
    sourceId: "usgs-earthquakes",
    category: "seismic",
    title: "M 5.1 — northwest Pacific margin",
    summary: "Representative seismic event used while the live feed reconnects.",
    place: "Northwest Pacific",
    latitude: 46.2,
    longitude: 151.8,
    metric: 5.1,
    unit: "Mw",
    severity: 3,
    confidence: "verified",
    freshness: "sample",
    sample: true,
    minutesAgo: 18,
  },
  {
    id: "sample-fire-amazon",
    sourceId: "nasa-eonet",
    category: "climate",
    title: "Wildfire cluster",
    summary: "Representative NASA EONET geometry; open the provenance panel before reuse.",
    place: "South America",
    latitude: -10.8,
    longitude: -62.2,
    severity: 3,
    confidence: "reported",
    freshness: "sample",
    sample: true,
    minutesAgo: 44,
  },
  {
    id: "sample-cyclone-pacific",
    sourceId: "nasa-eonet",
    category: "climate",
    title: "Tropical system",
    summary: "Representative storm position shown only when upstream sources are unavailable.",
    place: "Western Pacific",
    latitude: 17.4,
    longitude: 132.1,
    severity: 4,
    confidence: "reported",
    freshness: "sample",
    sample: true,
    minutesAgo: 76,
  },
  {
    id: "sample-obis-whale",
    sourceId: "obis",
    category: "ocean",
    title: "Cetacean occurrence",
    summary: "Representative marine biodiversity observation.",
    place: "Southern Ocean",
    latitude: -52.1,
    longitude: 18.5,
    severity: 1,
    confidence: "reported",
    freshness: "sample",
    sample: true,
    minutesAgo: 119,
  },
  {
    id: "sample-gbif-ibex",
    sourceId: "gbif",
    category: "biosphere",
    title: "Himalayan ibex observation",
    summary: "Representative biodiversity record with generalized coordinates.",
    place: "Western Himalaya",
    latitude: 32.5,
    longitude: 77.4,
    severity: 1,
    confidence: "reported",
    freshness: "sample",
    sample: true,
    minutesAgo: 163,
  },
  {
    id: "sample-alert-atlantic",
    sourceId: "nws-alerts",
    category: "humanitarian",
    title: "Coastal weather alert",
    summary: "Representative public warning footprint.",
    place: "North Atlantic coast",
    latitude: 36.7,
    longitude: -75.5,
    severity: 2,
    confidence: "verified",
    freshness: "sample",
    sample: true,
    minutesAgo: 201,
  },
  {
    id: "sample-solar",
    sourceId: "swpc",
    category: "space",
    title: "Solar X-ray flux",
    summary: "Representative six-hour solar environment reading.",
    metric: 0.0000024,
    unit: "W/m²",
    severity: 2,
    confidence: "verified",
    freshness: "sample",
    sample: true,
    minutesAgo: 12,
  },
  {
    id: "sample-research",
    sourceId: "openalex",
    category: "knowledge",
    title: "New planetary systems research indexed",
    summary: "Representative OpenAlex research pulse.",
    severity: 1,
    confidence: "reported",
    freshness: "sample",
    sample: true,
    minutesAgo: 248,
  },
];

export function createDemoResponse(): SignalsResponse {
  const now = Date.now();
  return {
    generatedAt: new Date(now).toISOString(),
    mode: "sample",
    signals: demoSeeds.map(({ minutesAgo, ...signal }) => ({
      ...signal,
      observedAt: new Date(now - minutesAgo * 60_000).toISOString(),
    })),
    adapters: [
      "usgs-earthquakes",
      "nasa-eonet",
      "nws-alerts",
      "gbif",
      "inaturalist",
      "obis",
      "swpc",
      "reliefweb",
      "nasa-cmr",
      "openalex",
      "world-bank",
      "ripe-atlas",
    ].map((sourceId) => ({
      sourceId,
      state: "offline" as const,
      records: 0,
      latencyMs: 0,
      checkedAt: new Date(now).toISOString(),
      error: "Waiting for live response",
    })),
  };
}
