import type { SourceRegistryEntry } from "./types";

export const SOURCE_REGISTRY: SourceRegistryEntry[] = [
  {
    id: "usgs-earthquakes",
    name: "Earthquake Hazards",
    provider: "USGS",
    domain: "Earth systems",
    protocol: "GeoJSON / FDSN",
    auth: "None",
    cadence: "live",
    coverage: "Global",
    license: "US public domain",
    integration: "connected",
    url: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php",
    description: "Continuously updated earthquake locations, magnitudes and review status.",
  },
  {
    id: "nasa-eonet",
    name: "EONET Natural Events",
    provider: "NASA",
    domain: "Earth systems",
    protocol: "REST / GeoJSON",
    auth: "None",
    cadence: "nrt",
    coverage: "Global",
    license: "NASA open data",
    integration: "connected",
    url: "https://eonet.gsfc.nasa.gov/docs/v3",
    description: "Open storms, wildfires, volcanoes, floods and other natural events.",
  },
  {
    id: "nasa-cmr",
    name: "Earthdata CMR",
    provider: "NASA",
    domain: "Earth systems",
    protocol: "REST / UMM",
    auth: "None",
    cadence: "periodic",
    coverage: "Global",
    license: "Collection-specific",
    integration: "connected",
    url: "https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html",
    description: "Discovery layer for NASA Earth science collections and granules.",
  },
  {
    id: "nasa-gibs",
    name: "Global Imagery Browse Services",
    provider: "NASA",
    domain: "Earth systems",
    protocol: "WMTS / WMS",
    auth: "None",
    cadence: "nrt",
    coverage: "Global",
    license: "NASA open data",
    integration: "catalogued",
    url: "https://www.earthdata.nasa.gov/data/tools/gibs",
    description: "Satellite imagery layers optimized for interactive maps.",
  },
  {
    id: "copernicus-stac",
    name: "Copernicus Data Space",
    provider: "European Commission / ESA",
    domain: "Earth systems",
    protocol: "STAC / OData",
    auth: "Mixed",
    cadence: "nrt",
    coverage: "Global",
    license: "Copernicus free and open",
    integration: "catalogued",
    url: "https://documentation.dataspace.copernicus.eu/APIs/STAC.html",
    description: "Sentinel radar, optical, land, ocean and atmosphere products.",
  },
  {
    id: "planetary-computer",
    name: "Planetary Computer",
    provider: "Microsoft",
    domain: "Earth systems",
    protocol: "STAC",
    auth: "None",
    cadence: "periodic",
    coverage: "Global",
    license: "Collection-specific",
    integration: "catalogued",
    url: "https://planetarycomputer.microsoft.com/docs/reference/stac/",
    description: "Cloud-native environmental catalog with STAC assets.",
  },
  {
    id: "landsat-stac",
    name: "Landsat Collection",
    provider: "USGS",
    domain: "Earth systems",
    protocol: "STAC / M2M",
    auth: "Mixed",
    cadence: "periodic",
    coverage: "Global",
    license: "US public domain",
    integration: "catalogued",
    url: "https://www.usgs.gov/landsat-missions/spatiotemporal-asset-catalog-stac",
    description: "Long-duration land imagery for historical change analysis.",
  },
  {
    id: "open-topography",
    name: "OpenTopography",
    provider: "OpenTopography",
    domain: "Earth systems",
    protocol: "REST / COG",
    auth: "Free key",
    cadence: "archive",
    coverage: "Global",
    license: "Dataset-specific",
    integration: "key-needed",
    url: "https://opentopography.org/developers",
    description: "Terrain, elevation, lidar and bathymetric data access.",
  },
  {
    id: "open-meteo",
    name: "Open-Meteo",
    provider: "Open-Meteo",
    domain: "Climate & air",
    protocol: "REST / JSON",
    auth: "None",
    cadence: "live",
    coverage: "Global",
    license: "CC BY 4.0",
    integration: "connected",
    url: "https://open-meteo.com/en/docs",
    description: "Weather forecasts, history, climate, marine and air-quality models.",
  },
  {
    id: "nws-alerts",
    name: "Active Weather Alerts",
    provider: "NOAA / NWS",
    domain: "Climate & air",
    protocol: "GeoJSON / CAP",
    auth: "None",
    cadence: "live",
    coverage: "United States",
    license: "US public domain",
    integration: "connected",
    url: "https://www.weather.gov/documentation/services-web-api",
    description: "Official active warning geometries, severity and instructions.",
  },
  {
    id: "openaq",
    name: "OpenAQ",
    provider: "OpenAQ",
    domain: "Climate & air",
    protocol: "REST v3",
    auth: "Free key",
    cadence: "nrt",
    coverage: "Global",
    license: "Provider-specific",
    integration: "key-needed",
    url: "https://docs.openaq.org/",
    description: "Aggregated ground-level air-quality measurements.",
  },
  {
    id: "sensor-community",
    name: "Sensor.Community",
    provider: "Sensor.Community",
    domain: "Climate & air",
    protocol: "REST / CSV",
    auth: "None",
    cadence: "live",
    coverage: "Global",
    license: "ODbL",
    integration: "catalogued",
    url: "https://sensor.community/en/",
    description: "Citizen-run particulate and environmental sensor network.",
  },
  {
    id: "meteostat",
    name: "Meteostat",
    provider: "Meteostat",
    domain: "Climate & air",
    protocol: "Python / bulk",
    auth: "None",
    cadence: "periodic",
    coverage: "Global",
    license: "CC BY-NC 4.0",
    integration: "catalogued",
    url: "https://dev.meteostat.net/",
    description: "Historical weather observations and station metadata.",
  },
  {
    id: "copernicus-cds",
    name: "Climate Data Store",
    provider: "Copernicus / ECMWF",
    domain: "Climate & air",
    protocol: "REST / GRIB / NetCDF",
    auth: "Registration",
    cadence: "periodic",
    coverage: "Global",
    license: "Copernicus",
    integration: "key-needed",
    url: "https://cds.climate.copernicus.eu/how-to-api",
    description: "ERA5 reanalysis, climate observations and model datasets.",
  },
  {
    id: "cams",
    name: "Atmosphere Data Store",
    provider: "Copernicus CAMS",
    domain: "Climate & air",
    protocol: "REST / GRIB / NetCDF",
    auth: "Registration",
    cadence: "nrt",
    coverage: "Global",
    license: "Copernicus",
    integration: "key-needed",
    url: "https://ads.atmosphere.copernicus.eu/",
    description: "Pollution, aerosols, greenhouse gases and atmospheric forecasts.",
  },
  {
    id: "noaa-ndbc",
    name: "National Data Buoy Center",
    provider: "NOAA",
    domain: "Oceans & water",
    protocol: "REST / text / SOS",
    auth: "None",
    cadence: "live",
    coverage: "Global network",
    license: "US public domain",
    integration: "catalogued",
    url: "https://www.ndbc.noaa.gov/",
    description: "Wave, wind, pressure, temperature and buoy observations.",
  },
  {
    id: "obis",
    name: "Ocean Biodiversity Information System",
    provider: "OBIS / UNESCO",
    domain: "Oceans & water",
    protocol: "REST / GeoJSON",
    auth: "None",
    cadence: "periodic",
    coverage: "Global ocean",
    license: "Record-specific",
    integration: "connected",
    url: "https://api.obis.org/",
    description: "Marine species occurrences and survey records.",
  },
  {
    id: "argo",
    name: "Argo",
    provider: "Argo GDAC",
    domain: "Oceans & water",
    protocol: "ERDDAP / NetCDF",
    auth: "None",
    cadence: "nrt",
    coverage: "Global ocean",
    license: "Open with attribution",
    integration: "catalogued",
    url: "https://argo.ucsd.edu/data/",
    description: "Autonomous ocean profiles measuring temperature and salinity.",
  },
  {
    id: "noaa-erddap",
    name: "Ocean Observing ERDDAP",
    provider: "NOAA",
    domain: "Oceans & water",
    protocol: "ERDDAP / OPeNDAP",
    auth: "None",
    cadence: "nrt",
    coverage: "Global",
    license: "Dataset-specific",
    integration: "catalogued",
    url: "https://osmc.noaa.gov/erddap/index.html",
    description: "Standardized ocean tables, grids, drifters and profiles.",
  },
  {
    id: "usgs-water",
    name: "Water Data APIs",
    provider: "USGS",
    domain: "Oceans & water",
    protocol: "REST / OGC",
    auth: "None",
    cadence: "live",
    coverage: "United States",
    license: "US public domain",
    integration: "catalogued",
    url: "https://api.waterdata.usgs.gov/",
    description: "Streamflow, groundwater, water quality and site observations.",
  },
  {
    id: "gebco",
    name: "GEBCO Grid",
    provider: "GEBCO",
    domain: "Oceans & water",
    protocol: "WMS / NetCDF",
    auth: "None",
    cadence: "archive",
    coverage: "Global",
    license: "GEBCO terms",
    integration: "catalogued",
    url: "https://www.gebco.net/data-products/gebco-web-services",
    description: "Global ocean bathymetry and sub-ice topography.",
  },
  {
    id: "gbif",
    name: "Global Biodiversity Information Facility",
    provider: "GBIF",
    domain: "Living systems",
    protocol: "REST / Darwin Core",
    auth: "None",
    cadence: "periodic",
    coverage: "Global",
    license: "Record-specific",
    integration: "connected",
    url: "https://techdocs.gbif.org/en/openapi/v1/occurrence",
    description: "The largest connected index of species occurrence records.",
  },
  {
    id: "inaturalist",
    name: "iNaturalist Observations",
    provider: "iNaturalist",
    domain: "Living systems",
    protocol: "REST / JSON",
    auth: "None",
    cadence: "nrt",
    coverage: "Global",
    license: "Observation-specific",
    integration: "connected",
    url: "https://api.inaturalist.org/v1/docs/",
    description: "Recent citizen observations with community identifications.",
  },
  {
    id: "ebird",
    name: "eBird",
    provider: "Cornell Lab",
    domain: "Living systems",
    protocol: "REST / JSON",
    auth: "Free key",
    cadence: "nrt",
    coverage: "Global",
    license: "eBird terms",
    integration: "key-needed",
    url: "https://documenter.getpostman.com/view/664302/S1ENwy59",
    description: "Recent bird observations, hotspots and taxonomy.",
  },
  {
    id: "movebank",
    name: "Movebank",
    provider: "Max Planck Institute",
    domain: "Living systems",
    protocol: "REST / CSV",
    auth: "Mixed",
    cadence: "nrt",
    coverage: "Global",
    license: "Study-specific",
    integration: "catalogued",
    url: "https://github.com/movebank/movebank-api-doc",
    description: "Animal telemetry with study-level permissions and safeguards.",
  },
  {
    id: "motus",
    name: "Motus Wildlife Tracking",
    provider: "Birds Canada",
    domain: "Living systems",
    protocol: "REST / bulk",
    auth: "Registration",
    cadence: "nrt",
    coverage: "Global network",
    license: "Project-specific",
    integration: "catalogued",
    url: "https://motus.org/data/downloads",
    description: "Radio telemetry detections across a distributed receiver network.",
  },
  {
    id: "neon",
    name: "NEON Data",
    provider: "NSF NEON",
    domain: "Living systems",
    protocol: "REST / files",
    auth: "None",
    cadence: "periodic",
    coverage: "United States",
    license: "CC0",
    integration: "catalogued",
    url: "https://data.neonscience.org/data-api/",
    description: "Standardized ecological field, airborne and sensor observations.",
  },
  {
    id: "catalogue-of-life",
    name: "Catalogue of Life",
    provider: "Catalogue of Life",
    domain: "Living systems",
    protocol: "REST / ChecklistBank",
    auth: "None",
    cadence: "periodic",
    coverage: "Global",
    license: "Dataset-specific",
    integration: "catalogued",
    url: "https://api.checklistbank.org/",
    description: "Authoritative taxonomic names and global checklists.",
  },
  {
    id: "reliefweb",
    name: "ReliefWeb Disasters",
    provider: "UN OCHA",
    domain: "Disasters & society",
    protocol: "REST / JSON",
    auth: "None",
    cadence: "nrt",
    coverage: "Global",
    license: "ReliefWeb terms",
    integration: "connected",
    url: "https://apidoc.reliefweb.int/",
    description: "Curated disaster records, humanitarian reports and organizations.",
  },
  {
    id: "hdx-hapi",
    name: "HDX HAPI",
    provider: "UN OCHA",
    domain: "Disasters & society",
    protocol: "REST / JSON",
    auth: "None",
    cadence: "periodic",
    coverage: "Humanitarian contexts",
    license: "Dataset-specific",
    integration: "catalogued",
    url: "https://hapi.humdata.org/docs",
    description: "Standard humanitarian indicators, needs and operational data.",
  },
  {
    id: "gdelt",
    name: "GDELT",
    provider: "GDELT Project",
    domain: "Disasters & society",
    protocol: "REST / BigQuery / files",
    auth: "None",
    cadence: "live",
    coverage: "Global",
    license: "Open",
    integration: "catalogued",
    url: "https://www.gdeltproject.org/data.html",
    description: "Machine-coded global news events and media geography.",
  },
  {
    id: "world-bank",
    name: "World Development Indicators",
    provider: "World Bank",
    domain: "Disasters & society",
    protocol: "REST / JSON / XML",
    auth: "None",
    cadence: "periodic",
    coverage: "Global",
    license: "CC BY 4.0",
    integration: "connected",
    url: "https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information",
    description: "Population, development, climate, economy and public-service indicators.",
  },
  {
    id: "who-gho",
    name: "Global Health Observatory",
    provider: "WHO",
    domain: "Disasters & society",
    protocol: "OData / JSON",
    auth: "None",
    cadence: "periodic",
    coverage: "Global",
    license: "WHO terms",
    integration: "catalogued",
    url: "https://www.who.int/data/gho/info/gho-odata-api",
    description: "Aggregated public-health indicators and dimensions.",
  },
  {
    id: "swpc",
    name: "Space Weather Prediction Center",
    provider: "NOAA",
    domain: "Space & astronomy",
    protocol: "REST / JSON",
    auth: "None",
    cadence: "live",
    coverage: "Near-Earth space",
    license: "US public domain",
    integration: "connected",
    url: "https://www.swpc.noaa.gov/products-and-data",
    description: "Solar X-rays, energetic particles, geomagnetic conditions and forecasts.",
  },
  {
    id: "nasa-donki",
    name: "DONKI",
    provider: "NASA",
    domain: "Space & astronomy",
    protocol: "REST / JSON",
    auth: "Free key",
    cadence: "nrt",
    coverage: "Heliosphere",
    license: "NASA open data",
    integration: "key-needed",
    url: "https://api.nasa.gov/",
    description: "Solar flares, CMEs, geomagnetic storms and space-weather notifications.",
  },
  {
    id: "jpl-cneos",
    name: "CNEOS Close Approaches",
    provider: "NASA JPL",
    domain: "Space & astronomy",
    protocol: "REST / JSON",
    auth: "None",
    cadence: "nrt",
    coverage: "Solar System",
    license: "NASA open data",
    integration: "catalogued",
    url: "https://ssd-api.jpl.nasa.gov/",
    description: "Near-Earth object close approaches, fireballs and impact monitoring.",
  },
  {
    id: "exoplanet-archive",
    name: "Exoplanet Archive",
    provider: "NASA / IPAC",
    domain: "Space & astronomy",
    protocol: "TAP / REST",
    auth: "None",
    cadence: "periodic",
    coverage: "Extrasolar systems",
    license: "NASA open data",
    integration: "catalogued",
    url: "https://exoplanetarchive.ipac.caltech.edu/docs/TAP/usingTAP.html",
    description: "Confirmed planets, host stars, transit and survey measurements.",
  },
  {
    id: "mast",
    name: "MAST",
    provider: "STScI",
    domain: "Space & astronomy",
    protocol: "REST / VO",
    auth: "None",
    cadence: "periodic",
    coverage: "Astronomical sky",
    license: "Mission-specific",
    integration: "catalogued",
    url: "https://mast.stsci.edu/api/v0/",
    description: "Hubble, JWST, TESS, Kepler and other mission observations.",
  },
  {
    id: "gaia",
    name: "Gaia Archive",
    provider: "ESA",
    domain: "Space & astronomy",
    protocol: "TAP / ADQL",
    auth: "None",
    cadence: "archive",
    coverage: "Milky Way",
    license: "ESA open data",
    integration: "catalogued",
    url: "https://gea.esac.esa.int/archive/",
    description: "Precise positions, motion and brightness for Milky Way sources.",
  },
  {
    id: "openalex",
    name: "OpenAlex",
    provider: "OurResearch",
    domain: "Knowledge & infrastructure",
    protocol: "REST / JSON",
    auth: "None",
    cadence: "periodic",
    coverage: "Global research",
    license: "CC0",
    integration: "connected",
    url: "https://docs.openalex.org/",
    description: "Scholarly works, institutions, concepts and citation graph.",
  },
  {
    id: "wikidata",
    name: "Wikidata Query Service",
    provider: "Wikimedia",
    domain: "Knowledge & infrastructure",
    protocol: "SPARQL",
    auth: "None",
    cadence: "periodic",
    coverage: "Global knowledge",
    license: "CC0",
    integration: "catalogued",
    url: "https://query.wikidata.org/",
    description: "Open linked facts for geographic and scientific enrichment.",
  },
  {
    id: "openstreetmap",
    name: "OpenStreetMap / Overpass",
    provider: "OpenStreetMap community",
    domain: "Knowledge & infrastructure",
    protocol: "Overpass QL / OSM XML",
    auth: "None",
    cadence: "nrt",
    coverage: "Global",
    license: "ODbL",
    integration: "catalogued",
    url: "https://wiki.openstreetmap.org/wiki/Overpass_API",
    description: "Open geographic features, places and infrastructure.",
  },
  {
    id: "ripe-atlas",
    name: "RIPE Atlas",
    provider: "RIPE NCC",
    domain: "Knowledge & infrastructure",
    protocol: "REST / streams",
    auth: "None",
    cadence: "live",
    coverage: "Global Internet",
    license: "RIPE terms",
    integration: "connected",
    url: "https://atlas.ripe.net/docs/apis/rest-api-manual/",
    description: "Distributed ping, traceroute, DNS and network measurements.",
  },
  {
    id: "crossref",
    name: "Crossref",
    provider: "Crossref",
    domain: "Knowledge & infrastructure",
    protocol: "REST / JSON",
    auth: "None",
    cadence: "periodic",
    coverage: "Global research",
    license: "Metadata-specific",
    integration: "catalogued",
    url: "https://api.crossref.org/",
    description: "Publication metadata, funding and persistent identifiers.",
  },
  {
    id: "ogd-india",
    name: "Open Government Data India",
    provider: "Government of India",
    domain: "India",
    protocol: "REST / CKAN / files",
    auth: "Mixed",
    cadence: "periodic",
    coverage: "India",
    license: "Government Open Data License",
    integration: "catalogued",
    url: "https://www.data.gov.in/apis",
    description: "Public datasets and APIs across Indian ministries and states.",
  },
  {
    id: "imd",
    name: "IMD Weather APIs",
    provider: "India Meteorological Department",
    domain: "India",
    protocol: "REST / files",
    auth: "Mixed",
    cadence: "live",
    coverage: "India",
    license: "IMD terms",
    integration: "catalogued",
    url: "https://mausam.imd.gov.in/responsive/apis.php",
    description: "Warnings, rainfall, cyclone and weather products for India.",
  },
  {
    id: "mosdac",
    name: "MOSDAC",
    provider: "ISRO",
    domain: "India",
    protocol: "REST / OGC / files",
    auth: "Registration",
    cadence: "nrt",
    coverage: "India and Indian Ocean",
    license: "Product-specific",
    integration: "key-needed",
    url: "https://www.mosdac.gov.in/",
    description: "Meteorological and oceanographic satellite products.",
  },
  {
    id: "bhuvan",
    name: "Bhuvan",
    provider: "ISRO / NRSC",
    domain: "India",
    protocol: "WMS / WMTS / APIs",
    auth: "Mixed",
    cadence: "periodic",
    coverage: "India",
    license: "Bhuvan terms",
    integration: "catalogued",
    url: "https://bhuvan.nrsc.gov.in/",
    description: "Indian satellite maps, thematic services and applications.",
  },
  {
    id: "incois",
    name: "INCOIS Ocean Data",
    provider: "INCOIS",
    domain: "India",
    protocol: "ERDDAP / files",
    auth: "Mixed",
    cadence: "nrt",
    coverage: "Indian Ocean",
    license: "Product-specific",
    integration: "catalogued",
    url: "https://incois.gov.in/",
    description: "Ocean state, waves, currents and coastal advisories.",
  },
  {
    id: "cpcb",
    name: "National Air Quality",
    provider: "CPCB",
    domain: "India",
    protocol: "Dashboard / data feeds",
    auth: "Mixed",
    cadence: "live",
    coverage: "India",
    license: "Government terms",
    integration: "catalogued",
    url: "https://cpcb.nic.in/",
    description: "Official air-quality measurements from Indian stations.",
  },
  {
    id: "cwc",
    name: "Central Water Commission",
    provider: "CWC",
    domain: "India",
    protocol: "Dashboard / bulletins",
    auth: "Mixed",
    cadence: "nrt",
    coverage: "India",
    license: "Government terms",
    integration: "catalogued",
    url: "https://cwc.gov.in/",
    description: "River levels, flood forecasts and reservoir bulletins.",
  },
];

export const CONNECTED_SOURCE_IDS = new Set(
  SOURCE_REGISTRY.filter((source) => source.integration === "connected").map(
    (source) => source.id,
  ),
);
